//! One specimen per cold canonical variant, including maximal-width operands.
//! These are codec fixtures, not executable bytecode: source validity belongs
//! to the canonical verifier, exercised separately with compiler output.
use crate::engine::code::bytecode::{
    ApplyKind, ArgumentsKind, DefineMethodKind, DynamicEnvironmentSource, EvalVariableSource,
    Instruction, IteratorCallKind, PrivateNameSource, WithObjectSource,
};

pub(super) fn instructions() -> Vec<Instruction> {
    vec![
        Instruction::PushAtomValueIndex(u32::MAX),
        Instruction::PushConst(u32::MAX),
        Instruction::FClosure(u32::MAX),
        Instruction::RegExp(u32::MAX),
        Instruction::SetName(u32::MAX),
        Instruction::ThrowReadOnly(u32::MAX),
        Instruction::ThrowRedeclaration(u32::MAX),
        Instruction::ThrowDeleteSuper,
        Instruction::PushThis,
        Instruction::PushActiveFunction,
        Instruction::PushHomeObject,
        Instruction::PushNewTarget,
        Instruction::Arguments(ArgumentsKind::Mapped),
        Instruction::Rest(u16::MAX),
        Instruction::VariableEnvironment,
        Instruction::HasEvalVariable {
            source: EvalVariableSource::Closure(u16::MAX),
            name: u32::MAX,
        },
        Instruction::GetEvalVariable {
            source: EvalVariableSource::Closure(u16::MAX),
            name: u32::MAX,
        },
        Instruction::PutEvalVariable {
            source: EvalVariableSource::Closure(u16::MAX),
            name: u32::MAX,
        },
        Instruction::DeleteEvalVariable {
            source: EvalVariableSource::Closure(u16::MAX),
            name: u32::MAX,
        },
        Instruction::DefineEvalVariable {
            source: EvalVariableSource::Closure(u16::MAX),
            name: u32::MAX,
        },
        Instruction::ToObject,
        Instruction::HasDynamicBinding {
            source: DynamicEnvironmentSource::With(WithObjectSource::Closure(u16::MAX)),
            name: u32::MAX,
        },
        Instruction::GetDynamicBinding {
            source: DynamicEnvironmentSource::With(WithObjectSource::Closure(u16::MAX)),
            name: u32::MAX,
        },
        Instruction::PutDynamicBinding {
            source: DynamicEnvironmentSource::With(WithObjectSource::Closure(u16::MAX)),
            name: u32::MAX,
        },
        Instruction::DeleteDynamicBinding {
            source: DynamicEnvironmentSource::With(WithObjectSource::Closure(u16::MAX)),
            name: u32::MAX,
        },
        Instruction::DynamicEnvironmentObject(DynamicEnvironmentSource::With(
            WithObjectSource::Closure(u16::MAX),
        )),
        Instruction::GlobalReference(u16::MAX),
        Instruction::GetRefValue(u32::MAX),
        Instruction::GetRefValueUndef(u32::MAX),
        Instruction::PutRefValue(u32::MAX),
        Instruction::GetLocal(u16::MAX),
        Instruction::PutLocal(u16::MAX),
        Instruction::SetLocal(u16::MAX),
        Instruction::SetLocalUninitialized(u16::MAX),
        Instruction::GetLocalCheck(u16::MAX),
        Instruction::InitializeLocal(u16::MAX),
        Instruction::InitializeDerivedLocal(u16::MAX),
        Instruction::PutLocalCheck(u16::MAX),
        Instruction::SetLocalCheck(u16::MAX),
        Instruction::GetArg(u16::MAX),
        Instruction::PutArg(u16::MAX),
        Instruction::SetArg(u16::MAX),
        Instruction::GetVarRef(u16::MAX),
        Instruction::PutVarRef(u16::MAX),
        Instruction::SetVarRef(u16::MAX),
        Instruction::GetVarRefCheck(u16::MAX),
        Instruction::PutVarRefCheck(u16::MAX),
        Instruction::InitializeVarRef(u16::MAX),
        Instruction::InitializeModuleImportCollision(u16::MAX),
        Instruction::InitializeDerivedVarRef(u16::MAX),
        Instruction::CloseLocal(u16::MAX),
        Instruction::GetVar(u16::MAX),
        Instruction::GetVarUndef(u16::MAX),
        Instruction::DeleteVar(u16::MAX),
        Instruction::PutVar(u16::MAX),
        Instruction::PutVarInit(u16::MAX),
        Instruction::InitializePrivateName(u16::MAX),
        Instruction::InitializePrivateMethod(u16::MAX),
        Instruction::InitializePrivateAccessor(u16::MAX),
        Instruction::GetPrivateField(PrivateNameSource::Closure(u16::MAX)),
        Instruction::GetPrivateField2(PrivateNameSource::Closure(u16::MAX)),
        Instruction::PutPrivateField(PrivateNameSource::Closure(u16::MAX)),
        Instruction::DefinePrivateField(PrivateNameSource::Closure(u16::MAX)),
        Instruction::PrivateIn(PrivateNameSource::Closure(u16::MAX)),
        Instruction::GetField(u32::MAX),
        Instruction::GetField2(u32::MAX),
        Instruction::GetArrayEl,
        Instruction::GetArrayEl2,
        Instruction::GetArrayEl3,
        Instruction::GetSuper,
        Instruction::GetSuperValue,
        Instruction::GetSuperValueForCall,
        Instruction::ArrayFrom(u16::MAX),
        Instruction::Object,
        Instruction::ToPropKey,
        Instruction::Insert2,
        Instruction::Insert3,
        Instruction::Dup3,
        Instruction::Insert4,
        Instruction::Perm3,
        Instruction::Perm4,
        Instruction::Perm5,
        Instruction::Rot4Left,
        Instruction::PutField(u32::MAX),
        Instruction::PutArrayEl,
        Instruction::PutSuperValue,
        Instruction::DefineField(u32::MAX),
        Instruction::DefineFieldComputed,
        Instruction::DefineMethod {
            key: u32::MAX,
            kind: DefineMethodKind::Getter,
            enumerable: true,
        },
        Instruction::DefineMethodComputed {
            kind: DefineMethodKind::Getter,
            enumerable: true,
        },
        Instruction::DefineClass {
            name: u32::MAX,
            has_heritage: true,
        },
        Instruction::InstallClassInstanceInitializer,
        Instruction::CallClassInstanceInitializer,
        Instruction::RunClassStaticInitializer,
        Instruction::CallClassStaticBlock,
        Instruction::DefineArrayEl,
        Instruction::SetNameComputed,
        Instruction::SetProto,
        Instruction::CopyDataProperties,
        Instruction::CopyDataPropertiesExcluded {
            target_depth: u8::MAX,
            source_depth: u8::MAX,
            excluded_depth: u8::MAX,
        },
        Instruction::Append,
        Instruction::Delete,
        Instruction::Drop,
        Instruction::Nip,
        Instruction::Swap,
        Instruction::Dup,
        Instruction::Dup1,
        Instruction::Neg,
        Instruction::Plus,
        Instruction::Inc,
        Instruction::Dec,
        Instruction::PostInc,
        Instruction::PostDec,
        Instruction::BitNot,
        Instruction::Not,
        Instruction::TypeOf,
        Instruction::IsUndefinedOrNull,
        Instruction::IsUndefined,
        Instruction::IsNull,
        Instruction::TypeOfIsUndefined,
        Instruction::TypeOfIsFunction,
        Instruction::Add,
        Instruction::Sub,
        Instruction::Mul,
        Instruction::Div,
        Instruction::Mod,
        Instruction::Pow,
        Instruction::Shl,
        Instruction::Sar,
        Instruction::Shr,
        Instruction::BitAnd,
        Instruction::BitXor,
        Instruction::BitOr,
        Instruction::Eq,
        Instruction::StrictEq,
        Instruction::Neq,
        Instruction::StrictNeq,
        Instruction::Lt,
        Instruction::Lte,
        Instruction::Gt,
        Instruction::Gte,
        Instruction::InstanceOf,
        Instruction::In,
        Instruction::IfFalse(u32::MAX),
        Instruction::IfTrue(u32::MAX),
        Instruction::Catch(u32::MAX),
        Instruction::DropCatch,
        Instruction::NipCatch,
        Instruction::Gosub(u32::MAX),
        Instruction::Ret,
        Instruction::DropGosub,
        Instruction::ForOfStart,
        Instruction::ForAwaitOfStart,
        Instruction::ForOfNext(u8::MAX),
        Instruction::ForAwaitOfNext,
        Instruction::IteratorGetValueDone,
        Instruction::ForInStart,
        Instruction::ForInNext,
        Instruction::IteratorClose,
        Instruction::IteratorClosePreserve,
        Instruction::IteratorDropPreserve,
        Instruction::IteratorDetachPreserve,
        Instruction::IteratorStart,
        Instruction::AsyncIteratorStart,
        Instruction::IteratorNext,
        Instruction::IteratorCall(IteratorCallKind::ThrowWithValue),
        Instruction::IteratorCheckObject,
        Instruction::InitialYield,
        Instruction::Yield,
        Instruction::YieldStar,
        Instruction::AsyncYieldStar,
        Instruction::Await,
        Instruction::ThrowIteratorMissingThrow,
        Instruction::Import,
        Instruction::Call(u16::MAX),
        Instruction::TailCall(u16::MAX),
        Instruction::Eval {
            argument_count: u16::MAX,
            environment: u16::MAX,
        },
        Instruction::CallMethod(u16::MAX),
        Instruction::TailCallMethod(u16::MAX),
        Instruction::Construct(u16::MAX),
        Instruction::MarkSuperCall,
        Instruction::ConstructSuper(u16::MAX),
        Instruction::CheckCtor,
        Instruction::InitDerivedConstructor,
        Instruction::Apply(ApplyKind::Construct),
        Instruction::ApplySuper,
        Instruction::ApplyEval {
            environment: u16::MAX,
        },
        Instruction::Return,
        Instruction::ReturnUndefined,
        Instruction::ReturnDerived(u16::MAX),
        Instruction::Throw,
    ]
}
